services:
  app:
    build: .
    ports: 
      - 3450:3450
    volumes:
      - .:/home/node/app

  db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
      ports:
    ports:
      - 4020:3306